# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dianfei.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dianfei.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdianfei.proto\x12\x07\x64ianfei\"n\n\x0cQueryRequest\x12\x0e\n\x06\x63\x61mpus\x18\x01 \x01(\t\x12\x10\n\x08\x62uilding\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t\x12\x11\n\tfeeitemid\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\t\"\x1b\n\nQueryReply\x12\r\n\x05value\x18\x01 \x01(\x01\x32W\n\x0e\x44ianFeiService\x12\x45\n\x17QueryCurrentElectricity\x12\x15.dianfei.QueryRequest\x1a\x13.dianfei.QueryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dianfei_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=136
  _globals['_QUERYREPLY']._serialized_start=138
  _globals['_QUERYREPLY']._serialized_end=165
  _globals['_DIANFEISERVICE']._serialized_start=167
  _globals['_DIANFEISERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
